// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCdbwEFRHU0un-830d1x-MSX47TYBqrVxI',
    appId: '1:970923262712:web:e68e70642f6a10466d310d',
    messagingSenderId: '970923262712',
    projectId: 'smart-parking-app-52d41',
    authDomain: 'smart-parking-app-52d41.firebaseapp.com',
    databaseURL: 'https://smart-parking-app-52d41-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'smart-parking-app-52d41.firebasestorage.app',
    measurementId: 'G-P7DGM0WQ3R',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDix291wjVcd7_kOoeF0UNIxkZrLfrqp_c',
    appId: '1:970923262712:android:674c9b82e342f6446d310d',
    messagingSenderId: '970923262712',
    projectId: 'smart-parking-app-52d41',
    databaseURL: 'https://smart-parking-app-52d41-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'smart-parking-app-52d41.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDiJ9LgJ8myIaXw2PhfCXr5_PSQbpjSSYs',
    appId: '1:970923262712:ios:8fcb195d4caa2fce6d310d',
    messagingSenderId: '970923262712',
    projectId: 'smart-parking-app-52d41',
    databaseURL: 'https://smart-parking-app-52d41-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'smart-parking-app-52d41.firebasestorage.app',
    iosBundleId: 'com.example.smartParking',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDiJ9LgJ8myIaXw2PhfCXr5_PSQbpjSSYs',
    appId: '1:970923262712:ios:8fcb195d4caa2fce6d310d',
    messagingSenderId: '970923262712',
    projectId: 'smart-parking-app-52d41',
    databaseURL: 'https://smart-parking-app-52d41-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'smart-parking-app-52d41.firebasestorage.app',
    iosBundleId: 'com.example.smartParking',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCdbwEFRHU0un-830d1x-MSX47TYBqrVxI',
    appId: '1:970923262712:web:226c15cc6067936b6d310d',
    messagingSenderId: '970923262712',
    projectId: 'smart-parking-app-52d41',
    authDomain: 'smart-parking-app-52d41.firebaseapp.com',
    databaseURL: 'https://smart-parking-app-52d41-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'smart-parking-app-52d41.firebasestorage.app',
    measurementId: 'G-FRLGEHH367',
  );
}
